version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: testdb
      MYSQL_ROOT_PASSWORD: rootpass
  python-app:
    image: python-app:latest
    environment:
      - MYSQL_USER=testuser
      - MYSQL_HOST=mysql
      - MYSQL_PASSWORD=testpass 
      - MYSQL_DBNAME=testdb
