version: 2.1
workflows:
  my_work_flow:
    jobs:
      - build
jobs:
  build:
    docker: 
      - image: cimg/python:3.8
    steps:
      - checkout
      - run: echo "Building ..."
      - setup_remote_docker
      - run: | 
          docker build -t "dyaaeldin/python-app:v1.0.0" .
          docker images