version: 2.1
workflows:
  my_work_flow:
    jobs:
      - build_test
jobs:
  build_test:
    docker: 
      - image: cimg/python:3.8
      - image: mysql:5.7
        environment:
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: rootpass
    steps:
      - checkout
      - run: echo "Building ..."
      - setup_remote_docker
      - run: docker build -t "dyaaeldin/python-app:v1.0.0" .
      - run: docker run -d -e "MYSQL_USER=testuser" -e "MYSQL_HOST=localhost" -e "MYSQL_PASSWORD=testpass" -e "MYSQL_DBNAME=testdb" dyaaeldin/python-app:v1.0.0 
      - run: curl http://localhost:5000























