version: 2.1
workflows:
  my_work_flow:
    jobs:
      - build_test
jobs:
  build_test:
    docker: 
      - image: cimg/python:3.8
      - image: mysql:5.7
        environment:
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
          MYSQL_DATABASE: testdb
          MYSQL_ROOT_PASSWORD: rootpass
    steps:
      - checkout
      - run: echo "Building ..."
      - run: apt-get update && apt-get install mysql-client
      - run: mysql -uroot -prootpass -e "show databases"





















